const ru = {
	logic: "Модули: ",
	vector: "Вектор",
	norm: "Нормализация",
	add: "Сложение",
	mul: "Умножение",
	draw: "Отображение",
	sub: "Вычитание",
	num: "Число",
	rot: "Установка вращения",
	settings: "Настройки",
	changeTheme: "Смена темы",
	changeGridScale: "Изменение масштаба сетки",
	changeGridSize: "Изменение размеров сетки",
	help: "Помощь",
	pos: "Начальная точка",
	changeLanguage: "Выбор языка",
	languageSelection: "Введите название языка: ",
	themeSelection: "Введите название темы (white/black): ",
	clear: "Очистить",
	numberQuestion:"Введите значение для числового блока: ",
	vectorXQuestion: "Введите значение для координаты X вектора: ",
	vectorYQuestion: "Введите значение для координаты Y вектора: ",
	thereIsAlready: "Уже есть такое соединение, отмена соединения",
	ringConnection: "Кольцевое соединение",
	parentNotConnected: "Модуль-родитель-вектор не подключен",
	parentNotVector: "Модуль-родитель не является вектором или не имеет связи с модулем-вектором",
	cannotBeConnected: "Этот модуль нельзя подключить",
	cannotBeConnectedTo: "К этому модулю нельзя подключить",
	screenshot: "Скриншот сохранён",
	fileName: "Введите имя сохраняемого файла: ",
	changeGridScaleQuestion: "Масштаб сетки ШxВ (у.е.): ",
	changeLanguageQuestion: "Введите название языка (en/ru): ",
	changeGridSizeQuestion: "Размер сетки ШxВ (px): "
}

const en = {
	logic: "Modules: ",
	vector: "Vector",
	norm: "Normalize",
	add: "Sum",
	mul: "Multiply",
	draw: "Display",
	sub: "Subtraction",
	num: "Number",
	rot: "Rotation",
	settings: "Settings",
	changeTheme: "Change theme",
	changeGridScale: "Change grid scale",
	changeGridSize: "Change grid size",
	help: "Help page",
	pos: "Start position",
	changeLanguage:"Change language",
	languageSelection: "Input name of language: ",
	themeSelection: "Input name of theme (white/black): ",
	clear: "Clear",
	numberQuestion:"Input value for number module: ",
	vectorXQuestion: "Input value for X-pos of vector: ",
	vectorYQuestion: "Input value for Y-pos of vector: ",
	thereIsAlready: "There is already such a connection, cancel the connection",
	ringConnection: "Ring connection",
	parentNotConnected: "Module-parent not connected",
	parentNotVector: "Module-parent not vector or not connected to module-vector",
	cannotBeConnected: "This module cannot be connected",
	screenshot: "Screenshot saved",
	fileName: "Input file name: ",
	changeGridScaleQuestion: "Size WxH (c.u.): ",
	changeLanguageQuestion:"Enter laguage name (en/ru): ",
	changeGridSize: "Grid size (px): "
}